name: Mirror Repo

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repo
        run: |
          git remote add mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zdundar-oraxai/OraxAICustomerPortal.git
          git push mirror main --force