name: Mirror Repo

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug token
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "TOKEN IS EMPTY ❌"
            exit 1
          else
            echo "TOKEN EXIST ✅"
          fi

      - name: Push to mirror repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          set -e

          echo "Starting mirror push..."

          git remote remove mirror || true

          git remote add mirror https://x-access-token:${TOKEN}@github.com/zdundar-oraxai/OraxAICustomerPortal.git

          git push mirror main

          echo "Mirror sync complete ✅"